### ISSUE TITLE
Console output keeping console color codes

### ISSUE THREAD

**Issue by HathHub** [InnateAlpaca/pterosocket#2]
Output I get when a player talks in one of the minecraft game servers:
`[20:15:12 INFO]: [38;2;170;170;170m[Default][38;2;255;255;255m[[38;2;255;170;0mPotatoland[m|[38;2;85;255;255mCyprus[m] [38;2;170;170;170mJuniorBoczek:[m u 2[m`

Would like a way to just getting string with no color formatting. Things like those [m and else could be fixed with `replace()` but the 34;45;178 and else are hard to get rid of.

**Comment by InnateAlpaca** [comment]
hmm, yea, I see. My suggestion here is trying to understand the logic that is behind the color formatting. Tbh from the 2 lines you sent I'm not quite sure to understand what that is. So if you knowy what is the name of that format, or if you have more examples of it you could write a function that correctly parses it (or maybe find some repository online that manages that for you), and then keep the message part alone. Otherwise try the replace() within theconsole_output listener.

Having only that single line I'm afraid I can't be of any further help.

**Comment by InnateAlpaca** [comment]
Okk, so I took a deeper look, and I suggest you to use [this](https://www.npmjs.com/package/ansicolor) library (which ofc you first need to install).
```js
const { strip } = require ('ansicolor')
socket.on('console_output', (data)=>{ 
    console.log(strip(data));
});
```
(very basic example to be implemented with the rest of the code you wanna add in that listener)

**Comment by HathHub** [comment]
I found out this really helpful:
`output.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g,"")`

Has fixed any ansi leftovers. Would like to see an option for monochromatic consoles too.

**Comment by InnateAlpaca** [comment]
Happy to see that you found a solution. I'd like to know if you have tested the use of ansicolor library, since correctly parsing the text is probably a cleaner solution than replacing individual strings. I used the library for that single line you gave me and it worked fine (need to remove the non-encoded beginning of the line "[20:15:12 INFO]: ", which has a fixed lenght tho... and maybe replace � with the correct character '\u001b' (but it shouldn't be necessary if you directly parse the string you get (I had to since I copied your string form the post).

**Comment by HathHub** [comment]
I got to test the library, however i personally will continue on using the regex methods, for plainly not depending on that library even though it works perfectly fine. This package has helped me achieve my goal, since other packages as nodeactyl are overcomplicated and lack of the event feature, leading you to use socket.io, which turns out to be not so friendly documentation. 
Wonderful project you have made.

**Comment by HathHub** [comment]
One thing that would be wonderful is retrieving file content with this. e.g: in server 1 I have a "groups.json" file. And possibly having a function added as pterosocket.file("./groups.json). Therefore being possible to retrieve content of file.

**Comment by InnateAlpaca** [comment]
Thanks! Yes I am working on that, there already is a [similar function](https://github.com/InnateAlpaca/pterosocket/blob/92edb1b918946bef49d74e30155871abcad43994/src/pterosocket.js#L17) in the github repository (haven't yet updated the npm nor the documentation). The reading-files works fine, but I'm having issues with writing files (which can still be done with sftp anyway). I will update the whole library as soon as I manage to make it work.
```js
// already working with the github repo
socket.apiRequest('files/list').then((data)=>{ ;
    var file_list= data;
});

const filename = 'allowlist.json';  //or whatever
socket.apiRequest(`files/contents?file=${filename}`).then((data)=>{   // not so good looking
    var my_file = data;
});
```
Of course you can use ```await``` if you add this within an async callback. This is also the function that is called to get the websocket credentials. As for a better-looking implementation of the whole pterodactyl api I'm not sure if I'll do that, since it would go far beyond the purpose of this repository: implementing the websocket api (which is the most problematic one).
